### ISSUE TITLE
Axis scaling?

### ISSUE THREAD

**Issue by ScottBrenner** [jorgemorgado/dashing-linechart#10]
Is it possible to change axis scaling for this widget, like making the Y-axis start at 0?

**Comment by mikle9** [comment]
Replace your options with the following in line_chart.coffee and you'll be able to scale the chart. 
I've set my min to 0 and max to 1

`options: $.extend({
        responsive: true
        maintainAspectRatio: true
        scales: {
            yAxes: [{
              ticks: {
               suggestedMax: 1
               suggestedMin: 0
               }
             }]
            }
`
