### ISSUE TITLE
Unable to set chart options

### ISSUE THREAD

**Issue by andystewart999** [jorgemorgado/dashing-linechart#3]
Hi Jorge - I'm using Dashing and have the default chart rendering OK, but I'm not able to set any of the options (for example pointDot, bezierCurve, showTooltips).

Looking at the .coffee file I see that you're reading anything in data-options but you've also hardcoded responsive and datasetStroke.  I've tried inserting additional options both in the .erb file and the .coffee file but they just don't appear to be getting read.

I've tried a number of variations in the .coffee file...

``` The default
   @myChart = new Chart(@ctx).Line(@myData, $.extend({
      responsive: false
      datasetStroke: true
    }, @get('options')))

`````` My adjustment (1st try)
  @myChart = new Chart(@ctx).Line(@myData, $.extend({
      responsive: false
      showTooltips: false
      datasetStroke: true
      pointDot: false
      bezierCurve: false
    }))

``` 2nd try
    @myChart = new Chart(@ctx).Line(@myData, {
      responsive: false,
      showTooltips: false,
      datasetStroke: true,
      pointDot: false,
      bezierCurve: false
    })

Here's an attempt via the .erb file...
 <div data-id="linechart" data-view="LineChart" data-title="" data-moreinfo="" data-options="bezierCurve: false"></div>

They all result in a chart being rendered so there's no real issue with syntax, just the total lack of options being applied.  I've also tried the full Chart.js instead of Chart.min.js.

Any thoughts?

Cheers,
Andy

**Comment by andystewart999** [comment]
I've been able to fix it via the job...  thanks!

  send_event('linechart',
        {
        labels: labels,
        datasets: [
                  {
                    label: 'Temperature',
                    fillColor: 'rgba(220,220,220,0.5)',
                    strokeColor: 'rgba(220,220,220,0.8)',
                    highlightFill: 'rgba(220,220,220,0.75)',
                    highlightStroke: 'rgba(220,220,220,1)',
                    data: Array.new(labels.length) { rand(15..40) },
                  },
                  {
                    label: 'Humidity',
                    fillColor: 'rgba(48,48,48,0)',
                    strokeColor: 'rgba(151,187,205,0.8)',
                    highlightFill: 'rgba(151,187,205,0.75)',
                    highlightStroke: 'rgba(151,187,205,1)',
                    data: Array.new(labels.length) { rand(25..75) },
                   }
                   ],
       options: {
                   scaleFontColor: '#555',
                   bezierCurve: true,
                   pointDot: false,
                   showTooltips: false,
                   showScale: true,
                   scaleOverride: true,
                   scaleStartValue: 0,
                   scaleStepWidth: 20,
                   scaleSteps: 5
                 }
        }
    )
end

**Comment by jorgemorgado** [comment]
Hi Andy. Sorry for the late reply. Being quite busy. Glad you managed to fix your issue.

I haven't tested any solution but the way I see it that some options can be passed to the chart constructor (when the chart is created). Not all options are supported here, you need to check the [documentation](http://www.chartjs.org/docs/). I even noticed that in the latest version of [Chart.js](http://www.chartjs.org/), `datasetStroke` has been removed. In my code, this is possible using the `options` hash.

Then, you can also pass the options at runtime as you did via a job. I have this documented in my [Line Chart example](https://github.com/jorgemorgado/dashing-linechart#usage) for the `scaleFontColor`.

It might be a good idea to pass global options to the constructor. That way, when the chart is rendered, it looks very close to the layout you wish - no need to wait for an scheduled job to run an re-render the chart to that layout. Then, keep passing those options via the job so the chart is rendered to that layout.
