### ISSUE TITLE
Widget don't show anything

### ISSUE THREAD

**Issue by Rudja971** [jorgemorgado/dashing-linechart#4]
Hello everyone! I am a beginner with dashing, and I need some help. I did all the steps and my widget don't show lines... I took your example. It is not my first try with dashing because I have succeed to display lists. 
Can someone help me pls?

**Comment by jorgemorgado** [comment]
Hi @Rudja971. To better help you, I really need more information about your setup. Browser name/version, Dashing version and everything you can think about to help me and other users to understand your problem. Like which error do you get on your browser's Javscript console?

**Comment by dimiii** [comment]
@Rudja971 Let me guess. The reason of issue is a missed step like adding 

```
  <script type="text/javascript" src="/assets/javascripts/Chart.min.js"></script>
```

into layout.erb ? 

@jorgemorgado  Thanks for the plugin!

**Comment by Rudja971** [comment]
Hi and thx for your response guys. 

Sorry for my late reply but you were pretty right @dimiii. It was a conflict between my different dashing project because I had different ways to access to Chart.min.js.

**Comment by johno1985** [comment]
Hi, I've just tried using this widget and I'm receiving the following error in the console:

**Comment by johno1985** [comment]
application.js:16783 Uncaught TypeError: (intermediate value).Line is not a function

**Comment by jorgemorgado** [comment]
Glad to know you have fixed the issue.
