### ISSUE TITLE
Update to work with latest Chart.js

### ISSUE THREAD

**Issue by SteveWells** [jorgemorgado/dashing-linechart#6]
See also https://github.com/jorgemorgado/dashing-barchart - here are the mods to make this work with latest dashing. 

```
@myChart = new Chart.Line(@ctx, {
  data: @myData,
  options: $.extend({
    responsive: false
    datasetStroke: true
    legend: {
      display: true
    }
  }, @get('options'))
});
```

I also had to change the onData function, but this might be to do with how I set up the data? I had to change 0..@myChart.dataset to 0..@myChart.data in the 2 for loops

 onData: (data) ->
    # Load new values, ie,
    #   @myChart.datasets[0].points[0].value = data.datasets[0].data[0]
    #   @myChart.datasets[0].points[1].value = data.datasets[0].data[1]
    #   ...
    #   @myChart.datasets[1].points[0].value = data.datasets[1].data[0]
    #   ...
    if @myChart && data.datasets
      for i in [0..@myChart.data.length - 1]
        for j in [0..@myChart.data[i].points.length - 1]
           @myChart.data[i].points[j].value = data.datasets[i].data[j]

```
  @myChart.update()
```

**Comment by jorgemorgado** [comment]
I've just released the new version with support for Chat.js v2. Thanks Steve!
