### ISSUE TITLE
Chart Colors will not render in Safari, or on raspberry pi

### ISSUE THREAD

**Issue by Brianm0440** [jorgemorgado/dashing-linechart#8]
Thanks jorgemorgado.
The chart works great for me in Chrome (see top portion of attached image), but will not render the colored lines in Safari, or on a raspberry pi (to display on a TV monitor).  See bottom portion of attached screen shot for view in Safari.  

Any suggestions?
<img width="606" alt="screen shot 2016-11-21 at 1 17 40 pm" src="https://cloud.githubusercontent.com/assets/2942578/20501075/1de027d2-afed-11e6-9aea-61f924733f3d.png">

note: when I run "inspect element" in the Safari browser, I see the following error message:
"Error: Unable to parse color from object ["rgba(255, 99, 132, 0.2)","rgba(255, 99, 132, 0.2)","rgba(255, 99, 132, 0.2)","rgba(255, 99, 132, 0.2)","rgba(255, 99, 132, 0.2)","rgba(255, 99, 132, 0.2)","rgba(255, 99, 132, 0.2)"]"

A google search for this error messages suggests that you have to use a double array in the data element to eliminate this problem.  But I haven't found a way to make that work yet.

**Comment by jorgemorgado** [comment]
Sorry but this is more a chartjs issue that really a widget problem. Maybe there's a way to pass that double array to the chart from the widget's parameters, but still, this is a chartjs question. I will keep the issue open for while in case you find and can post a solution. Maybe I have time to try the chart with Safari as well and let you know what I found. But you better ask this question to the chartjs team (if there's a way to get support from them).

**Comment by Brianm0440** [comment]
I found the solution:

The answer was exactly the opposite of the fix I suggested above.  The data load job did not need a double array, but rather one fewer arrays than the sample.  See bolded bracket characters below.  They are not necessary, and cause problems rendering in Safari (and on a raspberry pi).  If you remove these characters, the problem seems to be solved.  Sorry, the "bold" is difficult to see, and I can't highlight in this post.  It's the array brackets before and after the rgba statement.


labels = ['January', 'February', 'March', 'April', 'May', 'June', 'July']
data = [
  {
    label: 'First dataset',
    data: Array.new(labels.length) { rand(40..80) },
    backgroundColor: **[** 'rgba(255, 99, 132, 0.2)'  **]**  * labels.length,
    borderColor: **[** 'rgba(255, 99, 132, 1)' **]** * labels.length,
    borderWidth: 1,
  }, {
    label: 'Second dataset',
    data: Array.new(labels.length) { rand(40..80) },
    backgroundColor: **[** 'rgba(255, 206, 86, 0.2)' **]** * labels.length,
    borderColor: **[** 'rgba(255, 206, 86, 1)' **]** * labels.length,
    borderWidth: 1,
  }
]
options = { }

send_event('linechart', { labels: labels, datasets: data, options: options })
